### ISSUE TITLE
Error message displays when rotating IE belts

### ISSUE THREAD

**Issue by Golrith** [The-Acronym-Coders/MultiBlock-Stages#6] opened 2018-10-13 19:46 UTC
Seems to be a conflict when rotating the IE belts with the hammer, it triggers the MultiBlock Stages default error, but then proceeds to rotate the belt just fine.

Just causes an annoying chat spam of false errors.

**Comment by SkySom** [comment] 2018-10-16 14:55
Duplicate of #3

**Closed as completed by SkySom** 2018-10-16 14:55 UTC
Labels: Duplicate
